import { k8s, NamespacedAPIObject } from "@kubeframe/kubeframe-version";

interface PrometheusRuleSpec {

    /**
     * groups defines the content of Prometheus rule file
     */
    groups?: {
      /**
       * interval defines how often rules in the group are evaluated.
       */
      interval?: string;
      /**
       * labels define the labels to add or overwrite before storing the result for its rules.
       * The labels defined at the rule level take precedence.
       *
       * It requires Prometheus >= 3.0.0.
       * The field is ignored for Thanos Ruler.
       */
      labels?: {
        [k: string]: string;
      };
      /**
       * limit defines the number of alerts an alerting rule and series a recording
       * rule can produce.
       * Limit is supported starting with Prometheus >= 2.31 and Thanos Ruler >= 0.24.
       */
      limit?: number;
      /**
       * name defines the name of the rule group.
       */
      name: string;
      /**
       * partial_response_strategy is only used by ThanosRuler and will
       * be ignored by Prometheus instances.
       * More info: https://github.com/thanos-io/thanos/blob/main/docs/components/rule.md#partial-response
       */
      partial_response_strategy?: string;
      /**
       * query_offset defines the offset the rule evaluation timestamp of this particular group by the specified duration into the past.
       *
       * It requires Prometheus >= v2.53.0.
       * It is not supported for ThanosRuler.
       */
      query_offset?: string;
      /**
       * rules defines the list of alerting and recording rules.
       */
      rules?: {
        /**
         * alert defines the name of the alert. Must be a valid label value.
         * Only one of `record` and `alert` must be set.
         */
        alert?: string;
        /**
         * annotations defines annotations to add to each alert.
         * Only valid for alerting rules.
         */
        annotations?: {
          [k: string]: string;
        };
        /**
         * expr defines the PromQL expression to evaluate.
         */
        expr: number | string;
        /**
         * for defines how alerts are considered firing once they have been returned for this long.
         */
        for?: string;
        /**
         * keep_firing_for defines how long an alert will continue firing after the condition that triggered it has cleared.
         */
        keep_firing_for?: string;
        /**
         * labels defines labels to add or overwrite.
         */
        labels?: {
          [k: string]: string;
        };
        /**
         * record defines the name of the time series to output to. Must be a valid metric name.
         * Only one of `record` and `alert` must be set.
         */
        record?: string;
      }[];
    }[];
}

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The `PrometheusRule` custom resource definition (CRD) defines [alerting](https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/) and [recording](https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/) rules to be evaluated by `Prometheus` or `ThanosRuler` objects.
 *
 * `Prometheus` and `ThanosRuler` objects select `PrometheusRule` objects using label and namespace selectors.
 */
export interface PrometheusRuleProperties {
  metadata: {};
  /**
   * spec defines the specification of desired alerting rule definitions for Prometheus.
   */
  spec: PrometheusRuleSpec;
  /**
   * status defines the status subresource. It is under active development and is updated only when the
   * "StatusForConfigurationResources" feature gate is enabled.
   *
   * Most recent observed status of the PrometheusRule. Read-only.
   * More info:
   * https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
   */
  status?: {
    /**
     * bindings defines the list of workload resources (Prometheus, PrometheusAgent, ThanosRuler or Alertmanager) which select the configuration resource.
     */
    bindings?: {
      /**
       * conditions defines the current state of the configuration resource when bound to the referenced Workload object.
       */
      conditions?: {
        /**
         * lastTransitionTime defines the time of the last update to the current status property.
         */
        lastTransitionTime: string;
        /**
         * message defines the human-readable message indicating details for the condition's last transition.
         */
        message?: string;
        /**
         * observedGeneration defines the .metadata.generation that the
         * condition was set based upon. For instance, if `.metadata.generation` is
         * currently 12, but the `.status.conditions[].observedGeneration` is 9, the
         * condition is out of date with respect to the current state of the object.
         */
        observedGeneration?: number;
        /**
         * reason for the condition's last transition.
         */
        reason?: string;
        /**
         * status of the condition.
         */
        status: string;
        /**
         * type of the condition being reported.
         * Currently, only "Accepted" is supported.
         */
        type: "Accepted";
      }[];
      /**
       * group defines the group of the referenced resource.
       */
      group: "monitoring.coreos.com";
      /**
       * name defines the name of the referenced object.
       */
      name: string;
      /**
       * namespace defines the namespace of the referenced object.
       */
      namespace: string;
      /**
       * resource defines the type of resource being referenced (e.g. Prometheus, PrometheusAgent, ThanosRuler or Alertmanager).
       */
      resource: "prometheuses" | "prometheusagents" | "thanosrulers" | "alertmanagers";
    }[];
  };
}

export class PrometheusRule extends NamespacedAPIObject {
    spec: PrometheusRuleSpec;
    status?: { bindings?: { conditions?: { lastTransitionTime: string; message?: string; observedGeneration?: number; reason?: string; status: string; type: "Accepted"; }[]; group: "monitoring.coreos.com"; name: string; namespace: string; resource: "prometheuses" | "prometheusagents" | "thanosrulers" | "alertmanagers"; }[]; };

    constructor(properties: PrometheusRuleProperties) {
        super('monitoring.coreos.com/v1', 'PrometheusRule', properties.metadata);

            if (properties.spec === undefined) {
                throw new Error('Property spec is required by PrometheusRule');
            } else {
                this['spec'] = properties['spec'];
            }


            this['status'] = properties['status'];
    }
}
